Damasvin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path

from menu.views import DrinkListView, CoffeeCreateView, BubbleteaCreateView, DrinkUpdateView, DrinkDeleteView

app_name = 'menu'

urlpatterns = [
    path('', DrinkListView.as_view(), name='list'),
    path('add_coffee/', CoffeeCreateView.as_view(), name='add_coffee'),
    path('add_bubbletea/', BubbleteaCreateView.as_view(), name='add_bubbletea'),
    path('update/<int:pk>/', DrinkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', DrinkDeleteView.as_view(), name='delete'),
]

menu/models.py
from django.db import models


class Drink(models.Model):
    category = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    price = models.PositiveIntegerField()
    image = models.ImageField(blank=True, upload_to="menu/%Y/%m/%d/")  # default=menu/no_image.jpg

    def __str__(self):
        return f'카테고리: {self.category}, 이름: {self.name}, 가격: {self.price}'


class Coffee(Drink):
    pass


class Bubbletea(Drink):
    pass

menu/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from menu.models import Drink, Coffee, Bubbletea


class DrinkListView(ListView):  # drink_list.html
    model = Drink
    # paginate_by = 3


class CoffeeCreateView(CreateView):  # bookmark_form.html - form 이름이 흔해서 아래처럼 create로 바꿔준 거
    model = Coffee
    fields = '__all__'  # ['category', 'name', 'price', 'image']
    template_name = 'menu/drink_create.html'
    success_url = reverse_lazy('menu:list')
    initial = {'category': 'Coffee'}


class BubbleteaCreateView(CreateView):  # bookmark_form.html - form 이름이 흔해서 아래처럼 create로 바꿔준 거
    model = Bubbletea
    fields = '__all__'  # ['category', 'name', 'price', 'image']
    template_name = 'menu/drink_create.html'
    success_url = reverse_lazy('menu:list')
    initial = {'category': 'Bubbletea'}


class DrinkUpdateView(UpdateView):
    model = Drink
    fields = '__all__'
    template_name_suffix = '_update'  #drink_update.html
    success_url = reverse_lazy('menu:list')


class DrinkDeleteView(DeleteView):
    model = Drink
    success_url = reverse_lazy('menu:list')

menu/templates/menu/drink_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Drink Confirm Delete</title>
</head>
<body>
    <h1>{{ drink }}</h1>
    {% if drink.image != '' %}
    <img src="{{ drink.image.url }}" alt="" width="200px">
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back()">Cancel</button>
    </form>
</body>
</html>

menu/templates/menu/drink_create.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Drink Add</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
    <button type="button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>

menu/templates/menu/drink_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Drink List</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>#</th>
        <th>Image</th>
        <th>Drink</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for drink in drink_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        {% if drink.image != '' %}
        <td><img src="{{ drink.image.url }}" alt="drink image" width="100px"></td>
        {% else %}
        <td>--------------</td>
        {% endif %}
        <td>{{ drink }}</td>
        <td><a href="{% url 'menu:update' pk=drink.id %}">Modify</a></td>
        <td><a href="{% url 'menu:delete' pk=drink.id %}">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{% url 'menu:add_coffee' %}">Add Coffee</a>
<a href="{% url 'menu:add_bubbletea' %}">Add Bubbletea</a>
</body>
</html>

menu/templates/menu/drink_update.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Drink</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Modify</button>
    <button type="button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>